name: Build
on:
  push:
  pull_request:
  release:
    types:
      - created

jobs:
  get-version:
    name: Version
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-latest'
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        # Fetch all branches and tags to determine semantic version
        fetch-depth: 0

    - name: Calculate Version
      id: version
      uses: paulhatch/semantic-version@v3
      with:
        format: "${major}.${minor}.${patch}+${increment}"

    - name: Create Artifact
      # You may pin to the exact commit or the version.
      # uses: 1arp/create-a-file-action@ee80edaa4741d9997dbe053e052329d4070c020c
      uses: 1arp/create-a-file-action@0.2
      with:
        file: ${{ steps.version.outputs.version }}.txt
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.version.outputs.version }}
        path: '**/*.txt'
        if-no-files-found: error
